---
- name: Instalar e configurar Apache em Linux
  hosts: linux
  become: true
  tasks:
    - name: Garantir que Apache esteja instalado
      ansible.builtin.package:
        name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
        state: present

    - name: Garantir que Apache esteja ativo
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
        state: started
        enabled: true

    - name: Liberar porta 80 no firewall (Rocky)
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Liberar porta 80 no firewall (Ubuntu)
      ansible.builtin.ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_facts['os_family'] == 'Debian'
