---
- name: Instalar e configurar MySQL/MariaDB
  hosts: linux
  become: true
  vars:
    mysql_root_password: "SenhaForte123"
    mysql_test_db: "labdb"
    mysql_test_user: "labuser"
    mysql_test_password: "LabPass123"

  tasks:
    - name: Instalar pacotes MySQL/MariaDB
      ansible.builtin.package:
        name: "{{ 'mariadb-server' if ansible_facts['os_family'] == 'RedHat' else 'mysql-server' }}"
        state: present

    - name: Garantir que MySQL/MariaDB esteja ativo
      ansible.builtin.service:
        name: "{{ 'mariadb' if ansible_facts['os_family'] == 'RedHat' else 'mysql' }}"
        state: started
        enabled: true

    - name: Criar arquivo .my.cnf para root
      ansible.builtin.copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user=root
          password={{ mysql_root_password }}
        owner: root
        group: root
        mode: '0600'

    - name: Definir senha do root (somente localhost)
      community.mysql.mysql_user:
        name: root
        host: "localhost"
        password: "{{ mysql_root_password }}"
        login_unix_socket: "{{ '/var/lib/mysql/mysql.sock' if ansible_facts['os_family'] == 'RedHat' else '/var/run/mysqld/mysqld.sock' }}"
        state: present

    - name: Criar database de teste MySQL
      community.mysql.mysql_db:
        name: "{{ mysql_test_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Criar usuário de teste MySQL
      community.mysql.mysql_user:
        name: "{{ mysql_test_user }}"
        password: "{{ mysql_test_password }}"
        priv: "{{ mysql_test_db }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
