---
- name: Instalar e configurar PostgreSQL
  hosts: linux
  become: true
  vars:
    postgres_db: "labpg"
    postgres_user: "pguser"
    postgres_password: "PgPass123"

  tasks:
    ######################################################################
    # Instalação
    ######################################################################
    - name: Instalar PostgreSQL (server)
      ansible.builtin.package:
        name: "{{ 'postgresql-server' if ansible_facts['os_family'] == 'RedHat' else 'postgresql' }}"
        state: present

    - name: Instalar pacotes extras (client/contrib)
      ansible.builtin.package:
        name: "{{ 'postgresql-contrib' if ansible_facts['os_family'] == 'RedHat' else 'postgresql-contrib' }}"
        state: present
      ignore_errors: true

    - name: Inicializar banco de dados PostgreSQL (somente RedHat)
      ansible.builtin.command: postgresql-setup --initdb
      when: ansible_facts['os_family'] == "RedHat"
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Garantir que PostgreSQL esteja ativo
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    ######################################################################
    # Configuração
    ######################################################################
    - name: Criar database de teste PostgreSQL
      become_user: "{{ 'postgres' if ansible_facts['os_family'] != 'RedHat' else 'postgres' }}"
      community.postgresql.postgresql_db:
        name: "{{ postgres_db }}"
        state: present

    - name: Criar usuário de teste PostgreSQL
      become_user: "{{ 'postgres' if ansible_facts['os_family'] != 'RedHat' else 'postgres' }}"
      community.postgresql.postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        databases:
          - "{{ postgres_db }}"   # ✅ substitui o antigo "db"
        priv: ALL
        state: present
