---
- name: Validar bancos PostgreSQL e MySQL
  hosts: linux
  become: true

  tasks:
    ######################################################################
    # PostgreSQL
    ######################################################################
    - name: Obter informações dos bancos PostgreSQL
      become_user: postgres
      community.postgresql.postgresql_info:
      register: pg_info
      ignore_errors: true

    - name: Exibir bancos PostgreSQL
      debug:
        var: pg_info.databases
      when: pg_info is defined and not pg_info.failed

    ######################################################################
    # MySQL / MariaDB
    ######################################################################
    - name: Validar bancos MySQL
      community.mysql.mysql_info:
        login_user: root
        login_password: "SenhaForte123"
      register: mysql_info
      ignore_errors: true

    - name: Exibir bancos MySQL
      debug:
        var: mysql_info.databases
      when: mysql_info is defined and not mysql_info.failed
