---
- name: Validar bancos de dados MySQL/MariaDB e PostgreSQL
  hosts: linux
  become: true
  vars:
    mysql_root_password: "SenhaForte123"
    postgres_user: "postgres"

  tasks:
    ######################################################################
    # MySQL / MariaDB
    ######################################################################
    - name: Validar conexão MySQL/MariaDB
      ansible.builtin.command: >
        mysql -u root -p{{ mysql_root_password }} -e "SHOW DATABASES;"
      register: mysql_output
      changed_when: false
      ignore_errors: true

    - name: Exibir bancos MySQL/MariaDB
      ansible.builtin.debug:
        msg: "{{ mysql_output.stdout_lines }}"
      when: mysql_output.rc == 0

    ######################################################################
    # PostgreSQL
    ######################################################################
    - name: Validar conexão PostgreSQL
      ansible.builtin.command: >
        psql -U {{ postgres_user }} -d postgres -c "\l"
      register: postgres_output
      environment:
        PGPASSWORD: ""
      changed_when: false
      ignore_errors: true

    - name: Exibir bancos PostgreSQL
      ansible.builtin.debug:
        msg: "{{ postgres_output.stdout_lines }}"
      when: postgres_output.rc == 0
