---
- name: Validar bancos de dados MySQL e PostgreSQL
  hosts: linux
  become: true
  tasks:
    ######################################################################
    # Validação MySQL
    ######################################################################
    - name: Validar bancos MySQL
      community.mysql.mysql_info:
        login_user: root
        login_password: "SenhaForte123"
      register: mysql_info
      ignore_errors: true

    - name: Exibir bancos MySQL
      debug:
        var: mysql_info.databases
      when: mysql_info is defined and mysql_info.databases is defined

    ######################################################################
    # Validação PostgreSQL
    ######################################################################
    - name: Validar bancos PostgreSQL
      community.postgresql.postgresql_info:
        login_user: pguser
        login_password: "PgPass123"
        login_db: postgres     # 👈 aqui é o parâmetro correto
      register: pg_info
      become_user: postgres
      ignore_errors: true

    - name: Exibir bancos PostgreSQL
      debug:
        var: pg_info
      when: pg_info is defined
