---
# Lista inicial de collections 
# Inclui Linux, Windows e GCP, além de utilidades gerais.

collections:
  # Linux e módulos básicos
  - name: ansible.posix
  - name: community.general

  # Windows 
  - name: ansible.windows
  - name: community.windows
  - name: microsoft.iis

  # Containers
  - name: community.docker

  # Banco de dados 
  - name: community.mysql
  - name: community.postgresql 
    version: ">=3.2.0"

  # Segurança e criptografia
  - name: community.crypto

  # Cloud - Google
  - name: google.cloud
