---
all:
  children:
    linux:
      hosts:
        rocky:
          ansible_host: 192.168.0.140
          ansible_user: root
        ubuntu:
          ansible_host: 192.168.0.141
          ansible_user: root
        ubuntu2:
          ansible_host: 192.168.0.145
          ansible_user: root
        ubuntu3:
          ansible_host: 192.168.0.146
          ansible_user: root
