---
all:
  children:
    linux:
      children:
        rocky:
          hosts:
            rocky01:
              ansible_host: 192.168.0.140
            rocky02:
              ansible_host: 192.168.0.141
          vars:
            squid_port: 3128

        ubuntu:
          hosts:
            ubuntu01:
              ansible_host: 192.168.0.145
            ubuntu02:
              ansible_host: 192.168.0.146
          vars:
            http_port: 8080

      vars:
        ansible_port: 22
        ansible_user: root
        ansible_connection: ssh

    windows:
      hosts:
        windows01:
          ansible_host: 192.168.0.150
      vars:
        ansible_connection: winrm
        ansible_port: 5985         # 👈 alterado de 5986 para 5985
        ansible_user: Administrator
        ansible_password: "Proteu690201"   # ajuste sua senha real
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
